# Generated by Django 5.1.2 on 2025-06-18 07:58

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JigUnloadFTERTABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combine_lot_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of combined lot IDs', size=None)),
                ('lot_id', models.CharField(default=uuid.uuid4, editable=False, help_text='Auto-generated unique lot ID', max_length=50, unique=True)),
                ('total_case_qty', models.IntegerField(help_text='Total case quantity')),
            ],
        ),
        migrations.AddField(
            model_name='jigdetails',
            name='combined_lot_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='jigdetails',
            name='jig_unload_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jigunload_trayid',
            name='draft_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelmastercreation',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the model', max_length=100, null=True),
        ),
    ]
