# Generated by Django 5.2.1 on 2025-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0002_modelmastercreation_draft_saved_drafttrayid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmastercreation',
            name='dp_pick_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
